version: "{build}"
image: Visual Studio 2022
platform: x64

environment:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_NO_INTERACTION: "1"

install:
  - python -m pip install --upgrade pip
  - pip install poetry
  - poetry --version
  - poetry install --no-root

build_script:
  - poetry run python build.py build_ext --inplace

test_script:
  - poetry run python test_cython.py
