[project]
name = "virtmanager-win"
version = "0.1.0"
description = "A QEMU frontend built for windows using Qt & Pyside6"
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "cython>=3.1.6",
    "pyside6>=6.0.0",
    "numpy>=2.3.4",
    "setuptools>=65.0.0",
]

[tool.poetry.group.dev.dependencies]
black = ">=26.3.1"
flake8 = ">=7.3.0"
isort = ">=8.0.1"
mypy = ">=1.19.1"
pre-commit = ">=4.5.1"
pytest = ">=9.0.3"
